/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_sync_ NFMPI_SYNC
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_sync_ nfmpi_sync__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_sync_ nfmpi_sync
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_sync_ ( int *v1 ){
    int ierr;
    ierr = ncmpi_sync( *v1 );
    return ierr;
}
