.\" $Header$
.nr yr \n(yr+1900
.af mo 01
.af dy 01
.TH ncvalidator 1 "PnetCDF PNETCDF_RELEASE_VERSION" "Printed: \n(yr-\n(mo-\n(dy" "PnetCDF utilities"
.SH NAME
ncvalidator \- validates a classic netCDF file against CDF file formats
.SH SYNOPSIS
.ft B
.HP
ncvalidator
.nh
\%[-x]
\%[-t]
\%[-q]
\%[-h]
\%\fIfile\fP
.hy
.ft
.SH DESCRIPTION
\fBncvalidator\fP checks a netCDF file whether it conforms the classic CDF file formats.
If the input file is a valid NetCDF file, then a message of successful validation
is printed on command-line output, for example,
File "testfile.nc" is a valid NetCDF file.
Otherwise, a NetCDF error message is printed.
.SH OPTIONS
.IP "\fB-x\fP"
Repair the null-byte padding in file header. The null-byte padding is required by the NetCDF Classic Format Specifications. PnetCDF enforces this requirement, but NetCDF has never enforced it. This option checks the header for locations where null bytes are expected and replaces them with null bytes if non-null bytes are found. The repaired file is then conformed with the specification and allows both PnetCDF and NetCDF libraries to read the file without reporting error code NC_ENOTNC or NC_ENULLPAD. Noted that this repair is done in place and users might want to backup the input file first. Once the file is repaired, one may run ncmpidiff command to compare the contents of two files.
.IP "\fB-t\fP"
Turn on tracing mode, printing the progress of all successful metadata validation. When an error is detected, the tracing stops at the location of the error found.
.IP "\fB-q\fP"
Quiet mode - print nothing on the command-line output. When in quiet mode, users should check exit status. See below in "EXIT STATUS".
.IP "\fB-h\fP"
Print the available command-line options
.SH EXIT STATUS
An exit status of 0 means the file is conform with the classic CDF file format, and
1 means otherwise.
Note on VMS-based system, the exit status values are reversed.
.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR pnetcdf (3)
.SH DATE
PNETCDF_RELEASE_DATE
.LP

