.\" $Header$
.nr yr \n(yr+1900
.af mo 01
.af dy 01
.TH ncvalidator 1 "PnetCDF PNETCDF_RELEASE_VERSION" "Printed: \n(yr-\n(mo-\n(dy" "PnetCDF utilities"
.SH NAME
ncvalidator \- validates a classic netCDF file against CDF file formats
.SH SYNOPSIS
.ft B
.HP
ncvalidator
.nh
\%[-q]
\%[-h]
\%\fIfile\fP
.hy
.ft
.SH DESCRIPTION
\fBncvalidator\fP checks a netCDF file whether it conforms the classic CDF file formats.
If the input file is a valid NetCDF file, then a message of successful validation
is printed on command-line output, for example,
File "testfile.nc" is a valid NetCDF file.
Otherwise, a NetCDF error message is printed.
.SH OPTIONS
.IP "\fB-q\fP"
Quiet mode - print nothing on the command-line output. When in quiet mode, users should check exit status. See below in "EXIT STATUS".
.IP "\fB-h\fP"
Print the available command-line options
.SH EXIT STATUS
An exit status of 0 means no differences were found, and
1 means some differences were found.
Note on VMS-based system, the exit status values are reversed.
.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR pnetcdf (3)
.SH DATE
PNETCDF_RELEASE_DATE
.LP

