/* Do not edit this file. It is produced from the corresponding .m4 source */
/*
 *  Copyright (C) 2018, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 */
/* $Id$ */


#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>

#include <mpi.h>
#include <pnc_debug.h>
#include <common.h>
#include <ncchkio_driver.h>

int ncchkioiconvert(void *inbuf, void *outbuf, MPI_Datatype intype, MPI_Datatype outtype, int N) {
    int i;

    if (intype == MPI_BYTE){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_CHAR){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_SIGNED_CHAR){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((signed char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_UNSIGNED_CHAR){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((unsigned char*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_SHORT){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_UNSIGNED_SHORT){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((unsigned short*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_INT){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_UNSIGNED){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((unsigned int*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_FLOAT){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((float*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_DOUBLE){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((double*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_LONG_LONG_INT){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    if (intype == MPI_UNSIGNED_LONG_LONG){
        
        if (outtype == MPI_BYTE) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_CHAR) {
            for(i = 0; i < N; i++){
                ((char*)outbuf)[i] = (char)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((signed char*)outbuf)[i] = (signed char)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_CHAR) {
            for(i = 0; i < N; i++){
                ((unsigned char*)outbuf)[i] = (unsigned char)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_SHORT) {
            for(i = 0; i < N; i++){
                ((short*)outbuf)[i] = (short)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_SHORT) {
            for(i = 0; i < N; i++){
                ((unsigned short*)outbuf)[i] = (unsigned short)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_INT) {
            for(i = 0; i < N; i++){
                ((int*)outbuf)[i] = (int)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED) {
            for(i = 0; i < N; i++){
                ((unsigned int*)outbuf)[i] = (unsigned int)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_FLOAT) {
            for(i = 0; i < N; i++){
                ((float*)outbuf)[i] = (float)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_DOUBLE) {
            for(i = 0; i < N; i++){
                ((double*)outbuf)[i] = (double)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_LONG_LONG_INT) {
            for(i = 0; i < N; i++){
                ((long long*)outbuf)[i] = (long long)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        if (outtype == MPI_UNSIGNED_LONG_LONG) {
            for(i = 0; i < N; i++){
                ((unsigned long long*)outbuf)[i] = (unsigned long long)(((unsigned long long*)inbuf)[i]);
            }
            return NC_NOERR;
        }
        DEBUG_RETURN_ERROR(NC_EBADTYPE);;
    }
    DEBUG_RETURN_ERROR(NC_EBADTYPE);;

    return NC_NOERR;
}