.\" $Header$
.nr yr \n(yr+1900
.af mo 01
.af dy 01
.TH NCMPIVALID 1 2013-11-17 "Printed: \n(yr-\n(mo-\n(dy" "UTILITIES"
.SH NAME
ncmpivalid \- validates a netCDF file in parallel
.SH SYNOPSIS
.ft B
.HP
mpiexec -n 4 ncmpivalid
.nh
\%\fIfile\fP
.hy
.ft
.SH DESCRIPTION
\fBncmpivalid\fP checks a netCDF file whether it conforms
the CDF file format.

.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR pnetcdf (3)
.SH DATE
$Date$
.LP


