.\" $Header$
.nr yr \n(yr+1900
.af mo 01
.af dy 01
.TH ncmpivalid 1 "PnetCDF PNETCDF_RELEASE_VERSION" "Printed: \n(yr-\n(mo-\n(dy" "PnetCDF utilities"
.SH NAME
ncmpivalid \- validates a netCDF file in parallel
.SH SYNOPSIS
.ft B
.HP
mpiexec -n 4 ncmpivalid
.nh
\%\fIfile\fP
.hy
.ft
.SH DESCRIPTION
\fBncmpivalid\fP checks a netCDF file whether it conforms the CDF file format.
If the input file is a valid NetCDF file, then a message of successful validation
is printed on command-line output, for example,
File "testfile.nc" is a valid NetCDF file.
Otherwise, a NetCDF error message is printed.

.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR pnetcdf (3)
.SH DATE
PNETCDF_RELEASE_DATE
.LP

