.\" $Header$
.TH NCVALID 1
.SH NAME
ncvalid \- validates a netCDF file
.SH SYNOPSIS
.ft B
.HP
ncvalid
.nh
\%\fIfile\fP
.hy
.ft
.SH DESCRIPTION
\fBncvalid\fP checks a netCDF file whether it conforms
the CDF file format.

.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR netcdf (3)
.SH DATE
Fri September 27 10:35:07 2013
.SH AUTHOR
Wei-keng Liao
.LP


