.\" $Header$
.TH NCMPIDIFF 1
.SH NAME
ncmpidiff \- compares two netCDF files
.SH SYNOPSIS
.ft B
.HP
ncmpidiff
.nh
\%\fIfile1 file2\fP
.hy
.ft
.SH DESCRIPTION
\fBncmpidiff\fP compares the contents of the two files and reports
the first difference encountered to the standard output.

.SH "SEE ALSO"
.LP
.BR ncmpidump (1),
.BR netcdf (3)
.SH DATE
Thu may 13 16:13:07 2010
.SH AUTHOR
Wei-keng Liao
.LP


