/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_def_var_ NFMPI_DEF_VAR
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_def_var_ nfmpi_def_var__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_def_var_ nfmpi_def_var
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API void FORT_CALL nfmpi_def_var_ ( int *v1, char *v2 FORT_MIXED_LEN(d2), nc_type v3, int *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *ierr FORT_END_LEN(d2) ){
    *ierr = ncmpi_def_var( *v1, v2, v3, *v4, v5, v6 );
}
