/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_def_dim_ NFMPI_DEF_DIM
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_def_dim_ nfmpi_def_dim__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_def_dim_ nfmpi_def_dim
/* Else leave name alone */
#endif

FORTRAN_API void FORT_CALL nfmpi_def_dim_ ( int *v1, char *v2 FORT_MIXED_LEN(d2), int v3, int*v4, MPI_Fint *ierr FORT_END_LEN(d2) ){
    *ierr = ncmpi_def_dim( *v1, v2, v3, v4 );
}
