/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_get_vars_schar_ NFMPI_GET_VARS_SCHAR
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_get_vars_schar_ nfmpi_get_vars_schar__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_get_vars_schar_ nfmpi_get_vars_schar
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_get_vars_schar_ ( int *v1, int *v2, int v3[], int v4[], int v5[], char *v6 FORT_MIXED_LEN(d6) FORT_END_LEN(d6) ){
    int ierr;
    ierr = ncmpi_get_vars_schar( *v1, *v2, (const size_t *)(v3), (const size_t *)(v4), (const size_t *)(v5), v6 );
    return ierr;
}
