/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_inq_att_ NFMPI_INQ_ATT
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_inq_att_ nfmpi_inq_att__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_inq_att_ nfmpi_inq_att
/* Else leave name alone */
#endif

FORTRAN_API void FORT_CALL nfmpi_inq_att_ ( int *v1, int *v2, char *v3 FORT_MIXED_LEN(d3), nc_type*v4, size_t*v5, MPI_Fint *ierr FORT_END_LEN(d3) ){
    *ierr = ncmpi_inq_att( *v1, *v2, v3, v4, v5 );
}
