/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_inq_var_ NFMPI_INQ_VAR
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_inq_var_ nfmpi_inq_var__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_inq_var_ nfmpi_inq_var
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API void FORT_CALL nfmpi_inq_var_ ( int *v1, int *v2, char *v3 FORT_MIXED_LEN(d3), int *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *v7, MPI_Fint *ierr FORT_END_LEN(d3) ){
    int l2 = *v2 - 1;
    int *l6=0, ln6;

    ln6 = ncmpixVardim(*v1,*v2-1);
    if (ln6 > 0) {
        l6 = (size_t *)malloc( ln6 * sizeof(int) );
    }
    *ierr = ncmpi_inq_var( *v1, l2, v3, v4, v5, l6, v7 );

    {char *p = v3;
        while (*p) p++;
        while ((p-v3) < d3) { *p++ = ' '; }
    }

    if (l6) { 
	int li;
	if (!*ierr) {
            for (li=0; li<ln6; li++) 
                v6[li] = l6[ln6-1-li] + 1;
        }
        free(l6); }
}
