/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_inq_dimid_ NFMPI_INQ_DIMID
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_inq_dimid_ nfmpi_inq_dimid__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_inq_dimid_ nfmpi_inq_dimid
/* Else leave name alone */
#endif

FORTRAN_API void FORT_CALL nfmpi_inq_dimid_ ( int *v1, char *v2 FORT_MIXED_LEN(d2), int*v3, MPI_Fint *ierr FORT_END_LEN(d2) ){
    *ierr = ncmpi_inq_dimid( *v1, v2, v3 );
}
