/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=mpinetcdf.h -deffile=defs -debug
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define ncmpif_open_ NCMPIF_OPEN
#elif defined(F77_NAME_LOWER_2USCORE)
#define ncmpif_open_ ncmpif_open__
#elif !defined(F77_NAME_LOWER_USCORE)
#define ncmpif_open_ ncmpif_open
/* Else leave name alone */
#endif

FORTRAN_API void FORT_CALL ncmpif_open_ ( MPI_Fint *v1, char *v2 FORT_MIXED_LEN(d2), int *v3, MPI_Fint *v4, int*v5, MPI_Fint *ierr FORT_END_LEN(d2) )
{
    char *p2;

    {char *p = v2 + d2 - 1;
     int  li;
        while (*p == ' ') p--;
        p2 = (char *)malloc( p-v2 + 1 );
        for (li=0; li<(p-v2); li++) { p2[li] = v2[li]; }
        p2[li] = 0; 
    }
    *ierr = ncmpi_open( *v1, p2, *v3, *v4, v5 );
    free( p2 );
}
