/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_put_vars_long_ NFMPI_PUT_VARS_LONG
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_put_vars_long_ nfmpi_put_vars_long__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_put_vars_long_ nfmpi_put_vars_long
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_put_vars_long_ ( int *v1, int *v2, MPI_Offset v3[], MPI_Offset v4[], MPI_Offset v5[], long*v6 ){
    int ierr;
    ierr = ncmpi_put_vars_long( *v1, *v2, (const MPI_Offset *)(v3), (const MPI_Offset *)(v4), (const MPI_Offset *)(v5), v6 );
    return ierr;
}
