/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_put_var1_text_ NFMPI_PUT_VAR1_TEXT
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_put_var1_text_ nfmpi_put_var1_text__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_put_var1_text_ nfmpi_put_var1_text
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API void FORT_CALL nfmpi_put_var1_text_ ( int *v1, int *v2, int * v3[], char *v4 FORT_MIXED_LEN(d4), MPI_Fint *ierr FORT_END_LEN(d4) ){
    char *p4;

    {char *p = v4 + d4 - 1;
     int  li;
        while (*p == ' ' && p > v4) p--;
        p++;
        p4 = (char *)malloc( p-v4 + 1 );
        for (li=0; li<(p-v4); li++) { p4[li] = v4[li]; }
        p4[li] = 0; 
    }
    *ierr = ncmpi_put_var1_text( *v1, *v2, (const size_t *)(*v3), p4 );
    free( p4 );
}
