/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"


#ifdef F77_NAME_UPPER
#define nfmpi_put_att_text_ NFMPI_PUT_ATT_TEXT
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_put_att_text_ nfmpi_put_att_text__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_put_att_text_ nfmpi_put_att_text
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API void FORT_CALL nfmpi_put_att_text_ ( int *v1, int *v2, char *v3 FORT_MIXED_LEN(d3), int *v4, char *v5 FORT_MIXED_LEN(d5), MPI_Fint *ierr FORT_END_LEN(d3) FORT_END_LEN(d5) ){
    char *p3;
    size_t l4 = (size_t)v4;
    char *p5;

    {char *p = v3 + d3 - 1;
     int  li;
        while (*p == ' ' && p > v3) p--;
        p++;
        p3 = (char *)malloc( p-v3 + 1 );
        for (li=0; li<(p-v3); li++) { p3[li] = v3[li]; }
        p3[li] = 0; 
    }

    {char *p = v5 + d5 - 1;
     int  li;
        while (*p == ' ' && p > v5) p--;
        p++;
        p5 = (char *)malloc( p-v5 + 1 );
        for (li=0; li<(p-v5); li++) { p5[li] = v5[li]; }
        p5[li] = 0; 
    }
    *ierr = ncmpi_put_att_text( *v1, *v2, p3, l4, p5 );
    free( p3 );
    free( p5 );
}
