/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface -infile=../lib/pnetcdf.h -deffile=defs
 * DO NOT EDIT
 */
#include "mpinetcdf_impl.h"
#include "mvar.h"


#ifdef F77_NAME_UPPER
#define nfmpi_wait_all_ NFMPI_WAIT_ALL
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_wait_all_ nfmpi_wait_all__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_wait_all_ nfmpi_wait_all
/* Else leave name alone */
#endif


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"
FORTRAN_API int FORT_CALL nfmpi_wait_all_ ( int *v1, MPI_Fint * v2, MPI_Fint *v3 ){
    extern lnc_req *req_head ;
    extern lnc_req *req_tail ;
    int ierr;
    NCMPI_Request *l2_req;
    int i;
    lnc_req *tmp_req = NULL;
    l2_req = malloc((*v1)*sizeof(NCMPI_Request));
    tmp_req = req_head;
 
    i = 0;
    while(tmp_req != NULL){
	   l2_req[i]=  tmp_req->req; 
	   tmp_req = tmp_req->next;
	   i++; 
    }
  
    ierr = ncmpi_wait_all( *v1, l2_req, v3 );
   
    while(req_head != NULL){
           tmp_req = req_head;
	   req_head = req_head->next;
	   free(tmp_req);
    }    
	req_tail = NULL;

    free(l2_req);
	
    return ierr;
}
