.\" $Header$
.nr yr \n(yr+1900
.af mo 01
.af dy 01
.TH pnetcdf_version 1 "PnetCDF PNETCDF_RELEASE_VERSION" "Printed: \n(yr-\n(mo-\n(dy" "PnetCDF utilities"
.SH NAME
pnetcdf_version \- print the version information of PnetCDF library
.SH SYNOPSIS
.ft B
.HP
pnetcdf_version
.nh
\%[-v]
\%[-d]
\%[-c]
\%[-b]
\%[-h]
.hy
.ft
.SH DESCRIPTION
\fBpnetcdf_version\fP prints the version information of PnetCDF library and
the configure command line used to build the library

If no argument is given, all information is printed.
.SH OPTIONS
.IP "\fB-v\fP"
Version number of this PnetCDF release.
.IP "\fB-d\fP"
Release date.
.IP "\fB-c\fP"
Configure command-line arguments used to build this PnetCDF
.IP "\fB-b\fP"
MPI compilers used to build this PnetCDF library
.IP "\fB-h\fP"
Print the available command-line options of pnetcdf_version

.SH EXAMPLES
.LP
Print all information about the PnetCDF library by running the command with no options.

% pnetcdf_version
.sp
.nf
PnetCDF Version:    	PNETCDF_RELEASE_VERSION
PnetCDF Release date:	PNETCDF_RELEASE_DATE
PnetCDF configure: 	--with-mpi=/usr/local/bin
MPICC:  /usr/local/bin/mpicc -g -O2
MPICXX: /usr/local/bin/mpicxx -g -O2
MPIF77: /usr/local/bin/mpif77 -g -O2
MPIF90: /usr/local/bin/mpif90 -g -O2
.fi

.SH "SEE ALSO"
.LP
.BR pnetcdf (3)
.SH DATE
PNETCDF_RELEASE_DATE
.LP


