name: ubuntu_mpich

on:
  push:
    branches: master
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.1'
      - 'docs/*'
      - 'test/test_installed/*'
  pull_request:
    branches: master
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.1'
      - 'docs/*'
      - 'test/test_installed/*'

env:
   MPICH_VERSION: 4.2.0
   AUTOCONF_VERSION: 2.71
   AUTOMAKE_VERSION: 1.17
   LIBTOOL_VERSION: 2.5.4
   M4_VERSION: 1.4.19

jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v4
        - name: Set up dependencies
          run: |
            sudo apt-get update
            # install gfortran
            version=12
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-${version} gfortran-${version}
            sudo update-alternatives \
              --install /usr/bin/gcc gcc /usr/bin/gcc-${version} 100 \
              --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${version} \
              --slave /usr/bin/gcov gcov /usr/bin/gcov-${version}
            echo "---- gcc/gfortran version ------------------------------"
            which gcc
            which gfortran
            gcc --version
            gfortran --version
        - name: Clean up git untracked files
          run: |
            git clean -fx
        - name: Build GNU autotools
          run: |
            export PATH="${GITHUB_WORKSPACE}/AUTOTOOLS/bin:${PATH}"
            export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}/AUTOTOOLS/lib:${LD_LIBRARY_PATH}"
            cd ${GITHUB_WORKSPACE}
            wget -q https://ftp.gnu.org/gnu/m4/m4-${M4_VERSION}.tar.gz
            gzip -dc m4-${M4_VERSION}.tar.gz | tar -xf -
            cd m4-${M4_VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/AUTOTOOLS \
                        --silent
            make -s -j 8 install > qout 2>&1
            make -s -j 8 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
            wget -q https://ftp.gnu.org/gnu/autoconf/autoconf-${AUTOCONF_VERSION}.tar.gz
            gzip -dc autoconf-${AUTOCONF_VERSION}.tar.gz | tar -xf -
            cd autoconf-${AUTOCONF_VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/AUTOTOOLS \
                        --silent
            make -s -j 8 install > qout 2>&1
            make -s -j 8 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
            wget -q https://ftp.gnu.org/gnu/automake/automake-${AUTOMAKE_VERSION}.tar.gz
            gzip -dc automake-${AUTOMAKE_VERSION}.tar.gz | tar -xf -
            cd automake-${AUTOMAKE_VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/AUTOTOOLS \
                        --silent
            make -s -j 8 install > qout 2>&1
            make -s -j 8 distclean >> qout 2>&1
            cd ${GITHUB_WORKSPACE}
            wget -q https://ftp.gnu.org/gnu/libtool/libtool-${LIBTOOL_VERSION}.tar.gz
            gzip -dc libtool-${LIBTOOL_VERSION}.tar.gz | tar -xf -
            cd libtool-${LIBTOOL_VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/AUTOTOOLS \
                        --silent
            make -s -j 8 install > qout 2>&1
            make -s -j 8 distclean >> qout 2>&1
        - name: Build MPICH
          run: |
            cd ${GITHUB_WORKSPACE}
            echo "Install MPICH ${MPICH_VERSION} in ${GITHUB_WORKSPACE}/MPICH"
            rm -rf MPICH ; mkdir MPICH ; cd MPICH
            # git clone -q https://github.com/pmodels/mpich.git
            # cd mpich
            # git submodule update --init
            # ./autogen.sh
            wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz
            gzip -dc mpich-${MPICH_VERSION}.tar.gz | tar -xf -
            cd mpich-${MPICH_VERSION}
            ./configure --prefix=${GITHUB_WORKSPACE}/MPICH \
                        --silent \
                        --enable-romio \
                        --with-file-system=ufs \
                        --with-device=ch3:sock \
                        --enable-fortran \
                        CC=gcc FC=gfortran \
                        FFLAGS=-fallow-argument-mismatch \
                        FCFLAGS=-fallow-argument-mismatch
            make -s LIBTOOLFLAGS=--silent V=1 -j 4 install > qout 2>&1
            make -s -j 4 distclean >> qout 2>&1
        - name: Build PnetCDF
          run: |
            cd ${GITHUB_WORKSPACE}
            export PATH="${GITHUB_WORKSPACE}/AUTOTOOLS/bin:${PATH}"
            export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}/AUTOTOOLS/lib:${LD_LIBRARY_PATH}"
            m4 --version
            autoconf --version
            automake --version
            libtool --version
            autoreconf -i
            ./configure --prefix=${GITHUB_WORKSPACE}/PnetCDF \
                        --enable-option-checking=fatal \
                        --enable-profiling \
                        pnc_ac_debug=yes \
                        --enable-burst_buffering \
                        --enable-subfiling \
                        --enable-thread-safe \
                        --with-pthread \
                        --with-mpi=${GITHUB_WORKSPACE}/MPICH
            make -j 8 tests
        - name: Print config.log
          if: ${{ always() }}
          run: |
            cat ${GITHUB_WORKSPACE}/config.log
        - name: make check
          run: |
            cd ${GITHUB_WORKSPACE}
            make check
        - name: Print test log files
          if: ${{ always() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            fname=`find src test examples benchmarks -type f -name "*.log"`
            for f in $fname ; do \
               bname=`basename $f` ; \
               if test "x$bname" != xconfig.log ; then \
                  echo "-------- dump $f ----------------------------" ; \
                  cat $f ; \
               fi ; \
            done
        - name: make ptests
          run: |
            cd ${GITHUB_WORKSPACE}
            make ptests
        - name: make distcheck
          run: |
            cd ${GITHUB_WORKSPACE}
            make -j 8 distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --with-mpi=${GITHUB_WORKSPACE}/MPICH"
        - name: make install
          run: |
            cd ${GITHUB_WORKSPACE}
            prefix_path=${GITHUB_WORKSPACE}/pnetcdf_install
            echo "---- test make install prefix=${prefix_path}"
            make install prefix=${prefix_path}
            test/tst_install.sh ${prefix_path}
            prefix_path=pnetcdf_install
            destdir_path=${GITHUB_WORKSPACE}/inst/
            echo "---- test make install prefix=${prefix_path} DESTDIR=${destdir_path}"
            make install prefix=${prefix_path} DESTDIR=${destdir_path}
            test/tst_install.sh ${destdir_path}${prefix_path}
        - name: Cleanup
          if: ${{ always() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            make -s distclean
            rm -rf ${GITHUB_WORKSPACE}/pnetcdf_output
            rm -rf ${GITHUB_WORKSPACE}/MPICH
            rm -rf ${GITHUB_WORKSPACE}/pnetcdf_install
            rm -rf ${GITHUB_WORKSPACE}/inst

